title: 영국 생존 가이드
description: 한인들을 위한 영국 생존 가이드
theme: just-the-docs

favicon_ico: "/assets/flag-gb.ico"

nav_enabled: true
search_enabled: false

url: https://ukguide.shop

footer_content: "틀린 내용을 발견하거나 추가하고 싶은 내용이 있다면 <a href=\"https://salt-lace-abb.notion.site/341e6f37e0af80e88d12fc06d0ef4ea7?pvs=105\" target=\"_blank\">내용 추가/변경 요청하기</a>를 통해 알려주세요. 영국에서의 생활에 도움이 되는 정보를 함께 만들어가요!"

color_scheme: default
callouts:
  tip:
    title: 꿀팁 🍯
    color: yellow
  trouble:
    title: 시행착오 😵‍💫
    color: green
  term:
    title: 용어 정리 ℹ️
    color: blue

ga_tracking: G-RWC9EN0H8W
ga_tracking_anonymize_ip: true
